FROM mcr.microsoft.com/playwright:v1.58.0
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
RUN apt-get update && apt-get install -y make

ENV CI=true
ENV CONTAINER=true
WORKDIR /usr/src/app
RUN mkdir frontend

# Python dependencies
RUN --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-install-project

# Node.js dependencies
RUN --mount=type=bind,source=frontend/package.json,target=frontend/package.json \
    --mount=type=bind,source=frontend/package-lock.json,target=frontend/package-lock.json \
    --mount=type=cache,target=/root/.npm \
    cd frontend && npm ci

COPY . .
RUN make build
CMD ["sh", "-c", "uv run fava example/example.beancount frontend/tests/dashboards/*.beancount"]
